import { FastRateLimit } from 'fast-ratelimit';
import { nanoid } from 'nanoid';
import { Window } from './window.js';
import { CrawlerRenderer } from './crawler/index.js';

// _htmlBuffers.js is generated by scripts/build.js
import htmlBuffers from "./_htmlBuffers.js";

import { createConfig } from './config.js';
import { enqueueWindowInput, getWindow, registerWindow, deregisterWindow } from './state.js';

export function createRoot(rootFn) {
  let root = new Root(rootFn);
  let processEnv = globalThis.process && globalThis.process.env;

  root.configure(processEnv);

  return root;
}

class Root {

  constructor(rootFn) {
    this.rootFn = rootFn;

    this.externalWindowIdMapping = new Map();
    this.windowConnectionMap = new Map();
    this.config = null;
    this.rateLimitDisabled = false;
    this.messageLimiter = null;
    this.windowCreationLimiter = null;

    this.droppedMessagesCount = 0;

    /*
    setInterval(() => {
      if (this.droppedMessagesCount > 0) {
        console.log('Dropped messages: ' + this.droppedMessagesCount);
        this.droppedMessagesCount = 0;
      }
    }, 2000);
    */

    this.disableHtmlCompression = false;
  }

  hasWindow(windowId) {
    let window = getWindow(windowId);
    return window != null && !window.destroyed;
  }

  setRateLimit({ disabled }) {
    this.rateLimitDisabled = disabled;

    if (disabled) {
      // assign no-op rate limiters 
      this.messageLimiter = {
        consumeSync: () => true
      };

      this.windowCreationLimiter = {
        consumeSync: () => true
      };
    } else {
      this._configureRateLimiters();
    }
  }

  setDisableHtmlCompression() {
    this.disableHtmlCompression = true;
  }

  configure(env) {
    let previousConfig = this.config;
    let config = createConfig(env);
    let rateLimitConfigChanged = !previousConfig ||
      previousConfig.rateLimitWindowInputThreshold !== config.rateLimitWindowInputThreshold ||
      previousConfig.rateLimitWindowInputTtlSeconds !== config.rateLimitWindowInputTtlSeconds ||
      previousConfig.rateLimitWindowCreationThreshold !== config.rateLimitWindowCreationThreshold ||
      previousConfig.rateLimitWindowCreationTtlSeconds !== config.rateLimitWindowCreationTtlSeconds;

    this.config = config;
    this.crawlerRenderingEnabled = config.enableCrawlerRenderer;
    this.crawlerRenderer = this.crawlerRenderingEnabled ? (this.crawlerRenderer || new CrawlerRenderer()) : null;

    if (rateLimitConfigChanged && !this.rateLimitDisabled) {
      this._configureRateLimiters();
    }
  }

  _configureRateLimiters() {
    // TODO: we'll want to broadcast these limits to the client so it can
    // adjust its message sending rate.
    this.messageLimiter = new FastRateLimit({
      threshold: this.config.rateLimitWindowInputThreshold,
      ttl: this.config.rateLimitWindowInputTtlSeconds
    });

    this.windowCreationLimiter = new FastRateLimit({
      threshold: this.config.rateLimitWindowCreationThreshold,
      ttl: this.config.rateLimitWindowCreationTtlSeconds
    });
  }

  _enqueueMessage(windowId, message) {

    // apply global limit
    // TODO: move the length check to the websocket server's max message size
    // do this once we set up client-side rate limiting
    let isUnderLimit =
      this.messageLimiter.consumeSync(windowId) &&
      message.byteLength < this.config.maxInputEventBufferSize;

    // TODO: print on a regular interval the amount of messages that are being dropped
    if (!isUnderLimit) {
      this.droppedMessagesCount++;
      return;
    }

    // TODO: apply window & handler specific limits

    let inputBuffer = Buffer.from(message);
    let txPortId = inputBuffer.readUInt16LE(0);

    // portId of 0 is reserved for the pong command
    if (txPortId == 0) {
      let window = getWindow(windowId);

      if (window) {
        window.registerPong(inputBuffer);
      }
      return;
    }

    enqueueWindowInput(windowId, inputBuffer);
  }

  applyNewConnection(ws, { url, headers, ipAddress }, auxContext) {

    let params = new URLSearchParams(url.split('?')[1]);

    // then, get the values from the params object
    let externalWindowId = params.get('wi') || '';
    let readOffset = parseInt(params.get('ro'));
    let viewportSize = params.get('vs').split('x').map((num) => parseInt(num));
    let locationString = params.get('lo');

    let isUnderRateLimit = this.windowCreationLimiter.consumeSync(ipAddress);

    if (!isUnderRateLimit) {
      // 3010 is code for "excessive window creation" -- the client will close and not reconnect.
      ws.close(3010);
      return;
    }

    let cookieString = headers.get('cookie') || '';

    // href is the combination of:
    // - the protocol+hostname+port (take it from the Origin header for security)
    // - pathname
    // - searchParams
    let origin = headers.get('origin') || '';
    let href = origin + locationString;

    let pageParams = {
      windowId: null,
      href,
      viewportSize,
      readOffset,
      cookieString,
    };

    if (externalWindowId) {
      pageParams.windowId = externalWindowId;

      let windowId = this._convertExternalWindowIdToInternal(externalWindowId);

      if (this.hasWindow(windowId)) {
        this.reconnectWindow(ws, pageParams);
      } else {
        // 3001 is the code for "no such window" -- the client will reload and re-initialize for a new window
        ws.close(3001);
        return;
      }
    } else {
      let externalWindowId = nanoid();
      pageParams.windowId = externalWindowId;
      this.initWindow(ws, pageParams, auxContext);
    }
  }

  initWindow(ws, pageParams, auxContext) {

    // TODO: pass request's ip address here, and rate limit window creation based on ip address
    let window = new Window(this, pageParams, auxContext, this.rootFn, () => {});

    this.externalWindowIdMapping.set(pageParams.windowId, window.id);

    registerWindow(window);
    window.onBuffer(this._setupWsListeners(ws, window.id));

    window.start();

    window.onDestroy(() => {
      this.externalWindowIdMapping.delete(pageParams.windowId);
      deregisterWindow(window);
      this._closeWindowConnection(window.id);
    });

    window.startPingLoop(false);

  }

  async getHtmlResponse({ url, headers, ipAddress, isSecure, auxContext = null }) {
    let isUnderRateLimit = this.windowCreationLimiter.consumeSync(ipAddress);

    if (!isUnderRateLimit) {
      return {
        statusCode: 429,
        headers: {
          'Content-Type': 'text/plain',
          'Cache-Control': 'no-store',
        },
        body: 'Too many requests'
      }
    }

    let responseHeaders = {
      'Content-Type': 'text/html; charset=utf-8',
      'Vary': 'Accept',
      'Cache-Control': 'no-store',
    };

    if (this.crawlerRenderingEnabled && this.crawlerRenderer.shouldUseRenderer(headers)) {

      // href is combination of:
      // - the protocol+hostname+port 
      // - pathname
      // - searchParams

      // in cloudflare workers Service Worker mode, the url might contain the host
      // let's pick it out for now
      // TODO: clean up the flow
      if (!(url.startsWith('https://') || url.startsWith('http://'))) {
        url = (isSecure ? 'https://' : 'http://') + headers.get('host') + url;
      }

      let href = url;

      // TODO: check if we have a cached response for this request
      let html = await this.renderHtml({ headers, href, auxContext });
      responseHeaders['Content-Length'] = Buffer.byteLength(html);

      return {
        statusCode: 200,
        headers: responseHeaders,
        body: html
      };
    }

    let acceptEncoding = headers.get('accept-encoding') || '';
    let algo;
    let html;

    // in cloudflare workers, we need to be sending uncompressed HTML
    // seemingly CF doesn't support pre-compressed HTML
    if (this.disableHtmlCompression) {
      html = htmlBuffers.uncompressed;
    } else {
      if (acceptEncoding.indexOf('br') > -1) {
        algo = 'br';
        html = htmlBuffers.br;
      } else if (acceptEncoding.indexOf('gzip') > -1) {
        algo = 'gzip';
        html = htmlBuffers.gzip;
      } else {
        html = htmlBuffers.uncompressed;
      }
    }

    responseHeaders['Content-Length'] = html.byteLength;

    if (algo) {
      responseHeaders['Content-Encoding'] = algo;
    }

    return {
      statusCode: 200,
      headers: responseHeaders,
      body: html
    };
  }

  async renderHtml({ headers, href, auxContext = null }) {
    let cookieString = headers.get('cookie') || '';

    let pageParams = {
      windowId: nanoid(),
      href,

      // TODO: get viewport size from request
      viewportSize: [1920, 1080],

      readOffset: 0,
      cookieString
    };

    let htmlRenderContext = this.crawlerRenderer.createHtmlRenderingContext();

    let window = new Window(this, pageParams, auxContext, this.rootFn, buf => {
      htmlRenderContext.feedBuffer(buf);
    });

    registerWindow(window);

    window.start();

    window.onDestroy(() => {
      deregisterWindow(window);
    });

    return new Promise((resolve, reject) => {
      htmlRenderContext.onRenderComplete((html) => {
        window.destroy();
        resolve(html);
      });

      htmlRenderContext.onRenderError((err) => {
        window.destroy();
        reject(err);
      });
    });
  }

  _convertExternalWindowIdToInternal(externalWindowId) {
    return this.externalWindowIdMapping.get(externalWindowId);
  }

  reconnectWindow(ws, pageParams) {
    let windowId = this._convertExternalWindowIdToInternal(pageParams.windowId);

    let window = getWindow(windowId);

    if (!window || window.destroyed) {
      ws.close(3001);
      return;
    }

    // Only the newest websocket may publish to or disconnect this window.
    window.onBuffer(this._setupWsListeners(ws, windowId));

    window.startPingLoop(true);
    window.reconnect(pageParams);
  }

  _setupWsListeners(ws, windowId) {
    let previousConnection = this.windowConnectionMap.get(windowId);
    let connection = { ws };
    this.windowConnectionMap.set(windowId, connection);

    if (previousConnection && previousConnection.ws !== ws) {
      previousConnection.ws.close();
    }

    ws.on('message', async (message) => {
      if (this.windowConnectionMap.get(windowId) !== connection) {
        return;
      }
      this._enqueueMessage(windowId, message);
    });

    ws.on('close', () => {
      if (this.windowConnectionMap.get(windowId) !== connection) {
        return;
      }
      this.windowConnectionMap.delete(windowId);
      this.disconnectWindow(windowId);
    });

    return buf => {
      if (this.windowConnectionMap.get(windowId) === connection) {
        ws.send(buf);
      }
    };
  }

  _closeWindowConnection(windowId) {
    let connection = this.windowConnectionMap.get(windowId);

    if (connection) {
      this.windowConnectionMap.delete(windowId);
      connection.ws.close();
    }
  }

  disconnectWindow(windowId) {

    let window = getWindow(windowId);

    if (window) {
      window.disconnect();
    }
  }
}
